DROP TABLE IF EXISTS ApiKeys;
DROP TABLE IF EXISTS TicketsToTransactions;
DROP TABLE IF EXISTS TicketFlightSeats;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Flights;
DROP TABLE IF EXISTS AirPorts;
DROP TABLE IF EXISTS Franchises;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Tickets;

CREATE TABLE Users(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Username VARCHAR(50) ,
	Password VARCHAR(255),
	Epost VARCHAR(255),
	FirstName VARCHAR(255),
	LastName VARCHAR(255),
	City VARCHAR(255),
	ZipCode VARCHAR(25),
	Address VARCHAR(255),
	Grade TINYINT NOT NULL DEFAULT(1)
	CONSTRAINT AK_Username UNIQUE(Username) 
);

CREATE TABLE Franchises(
 	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 	Name VARCHAR(50) NOT NULL
);

CREATE TABLE AirPorts(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(255),
	Country VARCHAR(255),
	UTCOffset DECIMAL(4,2)
);

CREATE TABLE Transactions(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,	
	PaymentStatus VARCHAR(255),
	PaymentReferenceId VARCHAR(255)
);

CREATE TABLE Flights(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DepatureDate DATETIME,
	DeparturePort INT FOREIGN KEY REFERENCES AirPorts(ID),
	ArrivalDate DATETIME,
	ArrivalPort INT FOREIGN KEY REFERENCES AirPorts(ID)
);

CREATE TABLE TicketFlightSeats(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FlightID INT FOREIGN KEY REFERENCES Flights(ID),
);

CREATE TABLE Tickets(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	SeatID INT FOREIGN KEY REFERENCES TicketFlightSeats(ID),
	UserID INT FOREIGN KEY REFERENCES Users(ID),
	BookAt INT FOREIGN KEY REFERENCES Franchises(ID)
);

CREATE TABLE TicketsToTransactions(
	TicketID INT NOT NULL FOREIGN KEY REFERENCES Tickets(ID),
	TransactionID INT NOT NULL FOREIGN KEY REFERENCES Transactions(ID),
	primary key (TicketID, TransactionID)
);

CREATE TABLE ApiKeys(
<<<<<<< HEAD
	KeyValue VARCHAR(50) NOT NULL PRIMARY KEY,
	FranchiseID INT FOREIGN KEY REFERENCES Franchises(ID),
	Secret VARCHAR(50) NOT NULL,
=======
  KeyValue VARCHAR(50) NOT NULL PRIMARY KEY,
  Secret VARCHAR(50) NOT NULL,
  FranchiseID INT FOREIGN KEY REFERENCES Franchises(ID)
);

CREATE TABLE Franchises(
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name VARCHAR(50) NOT NULL
>>>>>>> origin/master
);